import { db } from '.'

export async function seedDatabase() {
  // Clear old data and reseed (schema changed)
  const count = await db.lots.count()
  if (count > 0) {
    // Check if data matches new schema
    const first = await db.lots.toCollection().first()
    if (first && 'lotBlock' in first) return // already seeded with real data
    // Wipe old sample data
    await Promise.all([
      db.lots.clear(),
      db.schedule.clear(),
      db.trades.clear(),
      db.emails.clear(),
    ])
  }

  const now = Date.now()

  // ═══════════════════════════════════════════════
  // REAL DATA — Patterson Ranch (8531) — Paige Beltran
  // Pulled from PCP Portal 2026-04-15
  // ═══════════════════════════════════════════════

  await db.lots.bulkAdd([
    {
      lotBlock: '12024',
      address: '501 Madelines Meadow Ln',
      plan: 'Hewitt 80080',
      planFull: '80080 Hewitt : Hewitt 80080',
      elevation: 'Elevation 27',
      scarStage: 'Final',
      productType: '1 Story',
      buyer: 'Katalina Ramirez',
      vfdDate: '2025-05-16',
      estFinish: '2025-08-21',
      currentTask: 'CM- Build Quality Celebration',
      taskDays: -84,
      updatedAt: '2026-04-07',
      createdAt: now,
    },
    {
      lotBlock: '13007',
      address: '120 Daniels Dusty Trl',
      plan: 'Mesilla 80120',
      planFull: '80120 Mesilla : Mesilla (80120)',
      elevation: 'Elevation R',
      scarStage: 'Final',
      productType: '2 Story',
      vfdDate: '2025-09-25',
      estFinish: '2025-11-21',
      currentTask: 'CM- Build Quality Celebration',
      taskDays: -62,
      updatedAt: '2026-02-14',
      createdAt: now,
    },
    {
      lotBlock: '17010',
      address: '536 Madelines Meadow Ln',
      plan: 'Sandalwood 80090',
      planFull: '80090 Sandalwood : Sandalwood (80090)',
      elevation: 'Elevation Z',
      scarStage: 'Final',
      productType: '2 Story',
      vfdDate: '2026-03-04',
      estFinish: '2026-02-18',
      currentTask: 'CM- Build Quality Pre-Closing Orientation',
      taskDays: -1,
      updatedAt: '2026-02-25',
      createdAt: now,
    },
    {
      lotBlock: '17009',
      address: '532 Madelines Meadow Ln',
      plan: 'Dinero 82230',
      planFull: '82230 Dinero : Dinero (82230)',
      elevation: 'Elevation HC201',
      scarStage: 'Final',
      productType: '2 Story',
      vfdDate: '2026-03-16',
      estFinish: '2026-03-24',
      currentTask: 'CM- Build Quality Pre-Closing Orientation',
      taskDays: -17,
      updatedAt: '2026-03-25',
      createdAt: now,
    },
    {
      lotBlock: '12017',
      address: '529 Madelines Meadow Ln',
      plan: 'Sandalwood 80090',
      planFull: '80090 Sandalwood : Sandalwood (80090)',
      elevation: 'Elevation R',
      scarStage: 'Final',
      productType: '2 Story',
      vfdDate: '2026-03-09',
      estFinish: '2026-03-30',
      currentTask: 'CM- Build Quality Pre-Closing Orientation',
      taskDays: -26,
      updatedAt: '2026-03-31',
      createdAt: now,
    },
    {
      lotBlock: '13014',
      address: '300 Daniels Dusty Trl',
      plan: 'Sandalwood 80090',
      planFull: '80090 Sandalwood : Sandalwood (80090)',
      elevation: 'Elevation R',
      scarStage: 'Second',
      productType: '2 Story',
      vfdDate: '2026-04-02',
      estFinish: '2026-03-23',
      currentTask: 'SCAR Final',
      taskDays: -3,
      updatedAt: '2026-03-30',
      createdAt: now,
    },
    {
      lotBlock: '02013',
      address: '549 Henry Milton Rd',
      plan: 'Sandalwood 80090',
      planFull: '80090 Sandalwood : Sandalwood (80090)',
      elevation: 'Elevation R',
      scarStage: 'Second',
      productType: '2 Story',
      vfdDate: '2026-05-01',
      estFinish: '2026-04-17',
      currentTask: 'GUTTERS- INSTALL GUTTERS COMPLETE',
      taskDays: -1,
      updatedAt: '2026-04-15',
      createdAt: now,
    },
    {
      lotBlock: '13017',
      address: '312 Daniels Dusty Trl',
      plan: 'Sandalwood 80090',
      planFull: '80090 Sandalwood : Sandalwood (80090)',
      elevation: 'Elevation Z',
      scarStage: 'Second',
      productType: '2 Story',
      vfdDate: '2026-05-14',
      estFinish: '2026-04-29',
      currentTask: 'Electrical- Hot Check',
      taskDays: 0,
      updatedAt: '2026-04-15',
      createdAt: now,
    },
    {
      lotBlock: '03002',
      address: '605 Henry Milton Rd',
      plan: 'Becket 80060',
      planFull: '80060 Becket : Becket 80060',
      elevation: 'Elevation R',
      scarStage: 'Second',
      productType: '1 Story',
      vfdDate: '2026-06-01',
      estFinish: '2026-05-14',
      currentTask: 'Flooring- Install Tile Flooring Day 1',
      taskDays: 0,
      updatedAt: '2026-04-15',
      createdAt: now,
    },
    {
      lotBlock: '12011',
      address: '540 Henry Milton Rd',
      plan: 'Dinero 82230',
      planFull: '82230 Dinero : Dinero (82230)',
      elevation: 'Elevation MD201',
      scarStage: 'Second',
      productType: '2 Story',
      vfdDate: '2026-06-19',
      estFinish: '2026-06-05',
      currentTask: 'Garage Door- Garage Door Install Complete',
      taskDays: -1,
      updatedAt: '2026-04-15',
      createdAt: now,
    },
    {
      lotBlock: '01009',
      address: '401 Mildred Prairie',
      plan: 'Sandalwood 80090',
      planFull: '80090 Sandalwood : Sandalwood (80090)',
      elevation: 'Elevation O',
      scarStage: 'Frame',
      productType: '2 Story',
      buyer: 'Leighton Bayola',
      vfdDate: '2026-06-25',
      estFinish: '2026-06-12',
      currentTask: 'LUMBER- DELIVER SIDING PACKAGE - WILL CALL BY CM',
      taskDays: -1,
      updatedAt: '2026-04-15',
      createdAt: now,
    },
    {
      lotBlock: '01007',
      address: '409 Mildred Prairie',
      plan: 'Hewitt 80080',
      planFull: '80080 Hewitt : Hewitt 80080',
      elevation: 'Elevation 27',
      scarStage: 'Frame',
      productType: '1 Story',
      vfdDate: '2026-07-01',
      estFinish: '2026-07-01',
      currentTask: 'Exterior Clean- Deliver Trash Box',
      taskDays: 0,
      updatedAt: '2026-04-15',
      createdAt: now,
    },
    {
      lotBlock: '02009',
      address: '533 Henry Milton Rd',
      plan: 'Hewitt 80080',
      planFull: '80080 Hewitt : Hewitt 80080',
      elevation: 'Elevation R',
      scarStage: 'Start',
      productType: '1 Story',
      vfdDate: '2026-08-10',
      estFinish: '2026-07-27',
      currentTask: 'Foundation- Install Cables Complete',
      taskDays: -1,
      updatedAt: '2026-04-15',
      createdAt: now,
    },
  ])

  // Sample trade contacts (Austin area)
  await db.trades.bulkAdd([
    { name: 'Torres Framing', company: 'Torres Framing LLC', contact: 'Mike Torres', phone: '(512) 555-0142', email: 'mike@torresframing.com', specialty: 'Framing' },
    { name: 'ABC Plumbing', company: 'ABC Plumbing Co', contact: 'Ray Chen', phone: '(512) 555-0198', email: 'ray@abcplumbing.com', specialty: 'Plumbing' },
    { name: 'Sparks Electric', company: 'Sparks Electrical', contact: 'Dana Sparks', phone: '(512) 555-0234', email: 'dana@sparkselectric.com', specialty: 'Electrical' },
    { name: 'Cool Air HVAC', company: 'Cool Air Systems', contact: 'James Wright', phone: '(512) 555-0311', email: 'james@coolair.com', specialty: 'HVAC' },
    { name: 'Pro Drywall', company: 'Pro Drywall & Texture', contact: 'Carlos Mendez', phone: '(512) 555-0455', email: 'carlos@prodrywall.com', specialty: 'Drywall' },
    { name: 'Lone Star Paint', company: 'Lone Star Painting', contact: 'Sarah Kim', phone: '(512) 555-0567', email: 'sarah@lonestarpaint.com', specialty: 'Paint' },
    { name: 'Hill Country Cabinets', company: 'Hill Country Cabinetry', contact: 'Tom Hill', phone: '(512) 555-0689', email: 'tom@hccabinets.com', specialty: 'Cabinets' },
    { name: 'Texas Stone Counters', company: 'Texas Stone & Surface', contact: 'Lisa Nguyen', phone: '(512) 555-0723', email: 'lisa@texasstone.com', specialty: 'Countertops' },
  ])

  // Sample emails tied to real lots
  await db.emails.bulkAdd([
    { lotId: 8, trade: 'Electrical', subject: 'Hot check scheduled - 312 Daniels Dusty Trl', from: 'dana@sparkselectric.com', date: '2026-04-15', snippet: 'Hey Paige, hot check is on for today at 312 Daniels Dusty. Inspector confirmed for 2pm.', flagged: true },
    { lotId: 7, trade: 'Gutters', subject: 'RE: Gutters complete - 549 Henry Milton', from: 'gutters@hillcountry.com', date: '2026-04-15', snippet: 'Crew finished gutters at 549 Henry Milton. Ready for your walkthrough whenever you get a chance.', flagged: true },
    { lotId: 11, subject: 'Siding package delivery - 401 Mildred Prairie', from: 'lumber@84lumber.com', date: '2026-04-15', snippet: 'Will call order ready for pickup. Need CM authorization to schedule delivery to lot 01009.', flagged: true },
    { subject: 'Weekly Schedule Update - Patterson Ranch', from: 'scheduling@pulte.com', date: '2026-04-14', snippet: 'Attached is the updated weekly schedule for Patterson Ranch. 3 lots flagged for potential delay.', flagged: false },
    { lotId: 13, trade: 'Foundation', subject: 'Cable install update - 533 Henry Milton', from: 'foundation@txconcrete.com', date: '2026-04-14', snippet: 'Post-tension cables installed. Ready for inspection. Slight delay due to weather yesterday.', flagged: false },
  ])

  console.log('[CommandCenter] Database seeded with real Patterson Ranch data — 13 lots')
}
